#!/bin/bash

# rr.shの有るディレクトリ
BASE_DIR=$(cd $(dirname $0); pwd)

if [ $# -eq 0 ] ; then
  source ${BASE_DIR}/module_list.sh
  exit 255
fi

if [ $# -ge 2 ]; then
    echo "引数多すぎ２個以上"
    exit 254
fi

ARG1=$1
IFS=':'
set -- ${ARG1}
MODULE=$1
COMMAND=$2

if [ $# -ge 3 ]; then
    echo "コマンドのコロンの数が多すぎ"
    exit 253
fi

if [ $# -eq 1 ]; then
    source ${BASE_DIR}/command_list.sh
    exit 0
fi

## aa:bbの時

# \e[36;40m\]\u\[\e[0m\]
RED_START="\e[31m"
RED_END="\e[m"

if [ -e ${BASE_DIR}/modules/${MODULE}/${COMMAND}/exec/exec.sh ]; then
    source ${BASE_DIR}/modules/${MODULE}/${COMMAND}/exec/exec.sh
else
    ERROR_TEXT="${LINENO}: Comman not find \"${MODULE}:${COMMAND}\""
    echo ${ERROR_TEXT}
    # echo -e "${RED_START}rr ${LINENO}: Comman not find \"${MODULE}:${COMMAND}\"${RED_END}"
    # echo "rr ${LINENO}: Comman not find \"${MODULE}:${COMMAND}\""
    exit 127
fi





